import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    // port: 3000,  // to change the port from default
    proxy: {
      "/test": "https://goldfish-app-wb78d.ondigitalocean.app",
      "/erase": "https://goldfish-app-wb78d.ondigitalocean.app",
      "/api/login": "https://goldfish-app-wb78d.ondigitalocean.app",
      "/api/validation": "https://goldfish-app-wb78d.ondigitalocean.app",
      "/profileData": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/api/userCreation":"https://goldfish-app-wb78d.ondigitalocean.app/api/userCreation",
      "/api/companylogin": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/api/companyCreation": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/companyProfileData": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/api/updateLogo": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/companyId": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/auth": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/profileId": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/reviews": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/updatePhoto": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/updateBioAndSkills": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/editIntro": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getSkills": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getValues": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getInterests": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getAllSkills": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getAllInterests": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getAllValues": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/addUserInterest": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getPendingFollowers": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/acceptFollowers": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/newConnection": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/checkFollow": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/addUserValues": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/updateCompanyInfo": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/updateCompanyMission": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getAllPros": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getPros": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getCons": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getCompanyReviews": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getDepartmentReviews": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getDepartment": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getAllDepartment": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/addDepartment": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/deleteDepartment": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/deleteDepartmentReview":"https://goldfish-app-wb78d.ondigitalocean.app/",
      "/deletePhoto": "https://goldfish-app-wb78d.ondigitalocean.app/",
      "/getFollowerInfo": "https://goldfish-app-wb78d.ondigitalocean.app/",
    },
  },
  plugins: [react()],
});
