import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    // port: 3000,  // to change the port from default
    proxy: {
      "/test": "http://localhost:8080",
      "/erase": "http://localhost:8080",
      "/api/login": "http://localhost:8080",
      "/api/validation": "http://localhost:8080",
      "/profileData": "http://localhost:8080",
      "/api/userCreation": "http://localhost:8080",
      "/api/companylogin": "http://localhost:8080",
      "/api/companyCreation": "http://localhost:8080",
      "/companyProfileData": "http://localhost:8080",
      "/api/updateLogo": "http://localhost:8080",
      "/companyId": "http://localhost:8080",
      "/auth": "http://localhost:8080",
      "/profileId": "http://localhost:8080",
      "/reviews": "http://localhost:8080",
      "/updatePhoto": "http://localhost:8080",
      "/updateBioAndSkills": "http://localhost:8080",
      "/editIntro": "http://localhost:8080",
      "/getSkills": "http://localhost:8080",
      "/getValues": "http://localhost:8080",
      "/getInterests": "http://localhost:8080",
      "/getAllSkills": "http://localhost:8080",
      "/getAllInterests": "http://localhost:8080",
      "/getAllValues": "http://localhost:8080",
      "/addUserInterest": "http://localhost:8080",
      "/getPendingFollowers": "http://localhost:8080",
      "/acceptFollowers": "http://localhost:8080",
      "/newConnection": "http://localhost:8080",
      "/checkFollow": "http://localhost:8080",
      "/addUserValues": "http://localhost:8080",
      "/updateCompanyInfo": "http://localhost:8080",
      "/updateCompanyMission": "http://localhost:8080",
      "/getAllPros": "http://localhost:8080",
      "/getPros": "http://localhost:8080",
      "/getCons": "http://localhost:8080",
      "/getCompanyReviews": "http://localhost:8080",
      "/getDepartmentReviews": "http://localhost:8080",
      "/getDepartment": "http://localhost:8080",
      "/editDepartment": "http://localhost:8080",
      "/getAllDepartment": "http://localhost:8080",
    },
  },
  plugins: [react()],
});
